version: '3'
services:
  # vote-now:
    # image: dinhvandung7541/vote-now:latest
    # depends_on: 
    #   - postgres
    # ports:
    #  - "8080:8080"

  postgres:
    image: postgres:9.5.14
    restart: always
    container_name: vote-now_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: vote-now
    ports:
      - 5432:5432
  
  postgres-test:
    image: postgres:9.5.14
    container_name: vote-now_db_test
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    ports:
      - 5439:5432

# networks:
#   default:
#     external:
#       name: nginx-proxy