version: '3'
services:
  vote-now:
    image: dinhvandung7541/vote-now:latest
    depends_on: 
      - postgres
    ports:
     - "8080:8080"

  postgres:
    image: postgres:latest
    restart: always
    container_name: vote-now_db_1
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: vote-now
      
    ports:
      - 5432:5432

# networks:
#   default:
#     external:
#       name: nginx-proxy