version: '3'
services:
  vote-now:
    build: .
    ports:
     - "5000:5000"

  postgres:
    image: postgres:10.4
    restart: always
    container_name: vote-now_db_1
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: vote-now-db

    ports:
      - 5432:5432