version: '3.1'

services:
  db:
    image: postgres:10.4
    restart: always
    container_name: vote-now_db_1
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: vote-now
    ports:
      - 5432:5432