// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Options   string
	Questions string
	Users     string
	Votes     string
}{
	Options:   "options",
	Questions: "questions",
	Users:     "users",
	Votes:     "votes",
}
