// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Options", testOptionsUpsert)

	t.Run("Questions", testQuestionsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("Votes", testVotesUpsert)
}
